version: "3.8"

services:
  api:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "25004:8000"
    environment:
      - DATABASE_TYPE=postgres
      - POSTGRES_PASSWORD=productsapi
      - POSTGRES_USER=productsapi
      - POSTGRES_DB=productsapi
      - DB_HOST=db
      - SECRET=your_secret_password
      - ALGORITHM=HS256
    networks:
      - internal_net
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=productsapi
      - POSTGRES_USER=productsapi
      - POSTGRES_DB=productsapi
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge